name: 'Apollo Studio: Validate and Publish Schema'
description: 'GitHub Action for validating and publishing your GraphQL schemas to Apollo Studio.'
inputs:
  args:
    description: 'Command to run'
    required: true
  apollo-key:
    description: 'Apollo Studio Key'
    required: true
  schema-variant:
    description: 'Schema Variant, defaults to current'
    required: true
    default: 'current'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
    - ${{ inputs.apollo-key }}
    - ${{ inputs.schema-variant }}
