name: 'test'

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install deps and build test server
        run: yarn install

      - name: Start Apollo Server
        shell: bash
        run: yarn start &

      - name: Wait for the server to start
        run: sleep 5

      - name: Validate Apollo Schema
        uses: ./
        with:
          action: validate
          apollo-key: ${{ secrets.APOLLO_KEY }}
          schema-variant: sandbox
